(function() {
var l=!0,o=null,v=!1;function C(){return function(){}}
(function(t){function m(){}function g(){}function E(a,b,d){var h,e="mixpanel"===d?t:t[d];if(e&&!c.isArray(e))s.error("You have already initialized "+d);else return h=new g,h.H(a,b,d),h.people=new m,h.people.H(h),A=A||h.e("debug"),c.d(e)||(h.F.call(h.people,e.people),h.F(e)),h}function k(a){this.props={};this.$=v;this.name=a.cookie_name?"mp_"+a.cookie_name:"mp_"+a.token+"_mixpanel";this.load();this.sa(a);this.$a(a);this.save()}function F(){this.la="submit"}function B(){this.la="click"}function w(){}
function x(){if(!x.Ga)J=x.Ga=l,K=v,c.a(y,function(a){a.xa()})}var I=Array.prototype,z=Object.prototype,L=I.slice,D=z.toString,G=z.hasOwnProperty,u=window.console,M=window.navigator,q=window.document,p=M.userAgent,O=["__mps","__mpa","__mpap","$people_distinct_id"],z=t&&t.__SV||0,H=window.XMLHttpRequest&&"withCredentials"in new XMLHttpRequest,K=!H&&-1==p.indexOf("MSIE"),c={},A=v,P={api_host:("https:"==q.location.protocol?"https://":"http://")+"api.mixpanel.com",cross_subdomain_cookie:l,cookie_name:"",
loaded:C(),store_google:l,save_referrer:l,test:v,img:v,track_pageview:l,debug:v,track_links_timeout:300,cookie_expiration:365,upgrade:v,disable_cookie:v,ip:l},J=v;(function(){var a=I.forEach,b=I.indexOf,d=Array.isArray,h={},e=c.a=function(b,d,c){if(b!=o)if(a&&b.forEach===a)b.forEach(d,c);else if(b.length===+b.length)for(var e=0,g=b.length;e<g&&!(e in b&&d.call(c,b[e],e,b)===h);e++);else for(e in b)if(G.call(b,e)&&d.call(c,b[e],e,b)===h)break};c.extend=function(a){e(L.call(arguments,1),function(b){for(var d in b)void 0!==
b[d]&&(a[d]=b[d])});return a};c.isArray=d||function(a){return"[object Array]"===D.call(a)};c.Na=function(a){try{return/^\s*\bfunction\b/.test(a)}catch(b){return v}};c.Ka=function(a){return!(!a||!G.call(a,"callee"))};c.m=function(a){return!a?[]:a.m?a.m():c.isArray(a)||c.Ka(a)?L.call(a):c.bb(a)};c.bb=function(a){var b=[];if(a==o)return b;e(a,function(a){b[b.length]=a});return b};c.eb=function(a){return a};c.ea=function(a,d){var c=v;if(a==o)return c;if(b&&a.indexOf===b)return-1!=a.indexOf(d);e(a,function(a){if(c||
(c=a===d))return h});return c};c.h=function(a,b){return-1!==a.indexOf(b)}})();c.ga=function(a,b){a.prototype=new b;a.Va=b.prototype};c.g=function(a){return a===Object(a)&&!c.isArray(a)};c.S=function(a){if(c.g(a)){for(var b in a)if(G.call(a,b))return v;return l}return v};c.d=function(a){return void 0===a};c.ha=function(a){return"[object String]"==D.call(a)};c.Ma=function(a){return"[object Date]"==D.call(a)};c.Oa=function(a){return"[object Number]"==D.call(a)};c.ca=function(a){c.a(a,function(b,d){c.Ma(b)?
a[d]=c.Ha(b):c.g(b)&&(a[d]=c.ca(b))});return a};c.Ha=function(a){function b(a){return 10>a?"0"+a:a}return a.getUTCFullYear()+"-"+b(a.getUTCMonth()+1)+"-"+b(a.getUTCDate())+"T"+b(a.getUTCHours())+":"+b(a.getUTCMinutes())+":"+b(a.getUTCSeconds())};c.pa=function(a){var b={};c.a(a,function(a,h){c.ha(a)&&0<a.length&&(b[h]=a)});return b};c.truncate=function(a,b){var d;"string"===typeof a?d=a.slice(0,b):c.isArray(a)?(d=[],c.a(a,function(a){d.push(c.truncate(a,b))})):c.g(a)?(d={},c.a(a,function(a,e){d[e]=
c.truncate(a,b)})):d=a;return d};c.p=function(){return!c.d(window.JSON)&&JSON.stringify?JSON.stringify:function(a){function b(a,c){var i="",j=0,f=j="",f=0,g=i,r=[],n=c[a];n&&"object"===typeof n&&"function"===typeof n.toJSON&&(n=n.toJSON(a));switch(typeof n){case "string":return d(n);case "number":return isFinite(n)?""+n:"null";case "boolean":case "null":return""+n;case "object":if(!n)return"null";i+="    ";r=[];if("[object Array]"===D.apply(n)){f=n.length;for(j=0;j<f;j+=1)r[j]=b(j,n)||"null";return f=
0===r.length?"[]":i?"[\n"+i+r.join(",\n"+i)+"\n"+g+"]":"["+r.join(",")+"]"}for(j in n)G.call(n,j)&&(f=b(j,n))&&r.push(d(j)+(i?": ":":")+f);return f=0===r.length?"{}":i?"{"+r.join(",")+""+g+"}":"{"+r.join(",")+"}"}}function d(a){var b=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,d={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};b.lastIndex=0;return b.test(a)?'"'+a.replace(b,function(a){var b=
d[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}return b("",{"":a})}}();c.U=function(){function a(){switch(f){case "t":return e("t"),e("r"),e("u"),e("e"),l;case "f":return e("f"),e("a"),e("l"),e("s"),e("e"),v;case "n":return e("n"),e("u"),e("l"),e("l"),o}i("Unexpected '"+f+"'")}function b(){for(;f&&" ">=f;)e()}function d(){var a,b,d="",c;if('"'===f)for(;e();){if('"'===f)return e(),d;if("\\"===f)if(e(),"u"===f){for(b=c=0;4>b;b+=1){a=parseInt(e(),
16);if(!isFinite(a))break;c=16*c+a}d+=String.fromCharCode(c)}else if("string"===typeof g[f])d+=g[f];else break;else d+=f}i("Bad string")}function h(){var a;a="";"-"===f&&(a="-",e("-"));for(;"0"<=f&&"9">=f;)a+=f,e();if("."===f)for(a+=".";e()&&"0"<=f&&"9">=f;)a+=f;if("e"===f||"E"===f){a+=f;e();if("-"===f||"+"===f)a+=f,e();for(;"0"<=f&&"9">=f;)a+=f,e()}a=+a;if(isFinite(a))return a;i("Bad number")}function e(a){a&&a!==f&&i("Expected '"+a+"' instead of '"+f+"'");f=r.charAt(j);j+=1;return f}function i(a){throw{name:"SyntaxError",
message:a,cb:j,text:r};}if(!c.d(window.JSON)&&JSON.parse)return JSON.parse;var j,f,g={'"':'"',"\\":"\\","/":"/",b:"\u0008",f:"\u000c",n:"\n",r:"\r",t:"\t"},r,n;n=function(){b();switch(f){case "{":var c;a:{var j,g={};if("{"===f){e("{");b();if("}"===f){e("}");c=g;break a}for(;f;){j=d();b();e(":");Object.hasOwnProperty.call(g,j)&&i('Duplicate key "'+j+'"');g[j]=n();b();if("}"===f){e("}");c=g;break a}e(",");b()}}i("Bad object")}return c;case "[":a:{c=[];if("["===f){e("[");b();if("]"===f){e("]");j=c;break a}for(;f;){c.push(n());
b();if("]"===f){e("]");j=c;break a}e(",");b()}}i("Bad array")}return j;case '"':return d();case "-":return h();default:return"0"<=f&&"9">=f?h():a()}};return function(a){r=a;j=0;f=" ";a=n();b();f&&i("Syntax error");return a}}();c.Y=function(a){var b,d,h,e,i=0,j=0,f="",f=[];if(!a)return a;a=c.ab(a);do b=a.charCodeAt(i++),d=a.charCodeAt(i++),h=a.charCodeAt(i++),e=b<<16|d<<8|h,b=e>>18&63,d=e>>12&63,h=e>>6&63,e&=63,f[j++]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(e);while(i<a.length);f=f.join("");switch(a.length%3){case 1:f=f.slice(0,-2)+"==";break;case 2:f=f.slice(0,-1)+"="}return f};c.ab=function(a){var a=(a+"").replace(/\r\n/g,"\n").replace(/\r/g,"\n"),b="",d,c,e=0,i;d=c=0;e=a.length;for(i=0;i<e;i++){var j=a.charCodeAt(i),f=o;128>j?c++:f=127<j&&2048>j?String.fromCharCode(j>>6|192,j&63|128):String.fromCharCode(j>>
12|224,j>>6&63|128,j&63|128);f!==o&&(c>d&&(b+=a.substring(d,c)),b+=f,d=c=i+1)}c>d&&(b+=a.substring(d,a.length));return b};c.wa=function(){function a(){function a(b,d){var c,e=0;for(c=0;c<d.length;c++)e|=i[c]<<8*c;return b^e}var b,c,i=[],j=0;for(b=0;b<p.length;b++)c=p.charCodeAt(b),i.unshift(c&255),4<=i.length&&(j=a(j,i),i=[]);0<i.length&&(j=a(j,i));return j.toString(16)}function b(){for(var a=1*new Date,b=0;a==1*new Date;)b++;return a.toString(16)+b.toString(16)}return function(){var d=(screen.height*
screen.width).toString(16);return b()+"-"+Math.random().toString(16).replace(".","")+"-"+a()+"-"+d+"-"+b()}}();c.La=function(){return/(google web preview|baiduspider|yandexbot)/i.test(p)?l:v};c.va=function(a){var b,d,h,e=[];"undefined"===typeof b&&(b="&");c.a(a,function(a,b){d=encodeURIComponent(a.toString());h=encodeURIComponent(b);e[e.length]=h+"="+d});return e.join(b)};c.da=function(a,b){var b=b.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]"),d=RegExp("[\\?&]"+b+"=([^&#]*)").exec(a);return d===o||
d&&"string"!==typeof d[1]&&d[1].length?"":decodeURIComponent(d[1]).replace(/\+/g," ")};c.cookie={get:function(a){for(var a=a+"=",b=q.cookie.split(";"),d=0;d<b.length;d++){for(var c=b[d];" "==c.charAt(0);)c=c.substring(1,c.length);if(0==c.indexOf(a))return decodeURIComponent(c.substring(a.length,c.length))}return o},parse:function(a){var b;try{b=c.U(c.cookie.get(a))||{}}catch(d){}return b},set:function(a,b,d,c){var f;var e="",i="";c&&(f=(e=(e=q.location.hostname.match(/[a-z0-9][a-z0-9\-]+\.[a-z\.]{2,6}$/i))?
e[0]:"")?"; domain=."+e:"",e=f);d&&(i=new Date,i.setTime(i.getTime()+864E5*d),i="; expires="+i.toGMTString());q.cookie=a+"="+encodeURIComponent(b)+i+"; path=/"+e},remove:function(a,b){c.cookie.set(a,"",-1,b)}};c.na=function(){function a(a,h,e){return function(i){if(i=i||b(window.event)){var j=l,f;c.Na(e)&&(f=e(i));i=h.call(a,i);if(v===f||v===i)j=v;return j}}}function b(a){if(a)a.preventDefault=b.preventDefault,a.stopPropagation=b.stopPropagation;return a}b.preventDefault=function(){this.returnValue=
v};b.stopPropagation=function(){this.cancelBubble=l};return function(b,c,e,i){b?b.addEventListener&&!i?b.addEventListener(c,e,v):(c="on"+c,b[c]=a(b,e,b[c])):s.error("No valid element provided to register_event")}}();c.Fa=function(){return function(a){if(!q.getElementsByTagName)return[];for(var a=a.split(" "),b,d=Array(q),h=0;h<a.length;h++)if(b=a[h].replace(/^\s+/,"").replace(/\s+$/,""),-1<b.indexOf("#")){b=b.split("#");var e=b[0],d=q.getElementById(b[1]);if(!d||e&&d.nodeName.toLowerCase()!=e)return[];
d=Array(d)}else if(-1<b.indexOf(".")){b=b.split(".");var e=b[0],i=b[1];e||(e="*");b=[];for(var j=0,f=0;f<d.length;f++){var g;g="*"==e?d[f].all?d[f].all:d[f].getElementsByTagName("*"):d[f].getElementsByTagName(e);for(var r=0;r<g.length;r++)b[j++]=g[r]}d=[];for(j=e=0;j<b.length;j++)b[j].className&&c.ha(b[j].className)&&b[j].className.match(RegExp("\\b"+i+"\\b"))&&(d[e++]=b[j])}else if(b.match(/^(\w*)\[(\w+)([=~\|\^\$\*]?)=?"?([^\]"]*)"?\]$/)){var e=RegExp.$1,n=RegExp.$2,i=RegExp.$3,k=RegExp.$4;e||(e=
"*");b=[];for(f=j=0;f<d.length;f++){g="*"==e?d[f].all?d[f].all:d[f].getElementsByTagName("*"):d[f].getElementsByTagName(e);for(r=0;r<g.length;r++)b[j++]=g[r]}d=[];e=0;switch(i){case "=":i=function(a){return a.getAttribute(n)==k};break;case "~":i=function(a){return a.getAttribute(n).match(RegExp("\\b"+k+"\\b"))};break;case "|":i=function(a){return a.getAttribute(n).match(RegExp("^"+k+"-?"))};break;case "^":i=function(a){return 0==a.getAttribute(n).indexOf(k)};break;case "$":i=function(a){return a.getAttribute(n).lastIndexOf(k)==
a.getAttribute(n).length-k.length};break;case "*":i=function(a){return-1<a.getAttribute(n).indexOf(k)};break;default:i=function(a){return a.getAttribute(n)}}d=[];for(j=e=0;j<b.length;j++)i(b[j])&&(d[e++]=b[j])}else{e=b;b=[];for(f=j=0;f<d.length;f++){g=d[f].getElementsByTagName(e);for(r=0;r<g.length;r++)b[j++]=g[r]}d=b}return d}}();c.info={Ba:function(){var a="",b={};c.a("utm_source utm_medium utm_campaign utm_content utm_term".split(" "),function(d){a=c.da(q.URL,d);a.length&&(b[d]=a)});return b},
Ra:function(a){return 0===a.search("https?://(.*)google.([^/?]*)")?"google":0===a.search("https?://(.*)bing.com")?"bing":0===a.search("https?://(.*)yahoo.com")?"yahoo":0===a.search("https?://(.*)duckduckgo.com")?"duckduckgo":o},Sa:function(a){var b=c.info.Ra(a),d={};if(b!==o)d.$search_engine=b,a=c.da(a,"yahoo"!=b?"q":"p"),a.length&&(d.mp_keyword=a);return d},Z:function(){var a=M.vendor||"";return window.opera?c.h(p,"Mini")?"Opera Mini":"Opera":/(BlackBerry|PlayBook|BB10)/i.test(p)?"BlackBerry":c.h(p,
"Chrome")?"Chrome":c.h(a,"Apple")?c.h(p,"Mobile")?"Mobile Safari":"Safari":c.h(p,"Android")?"Android Mobile":c.h(p,"Konqueror")?"Konqueror":c.h(p,"Firefox")?"Firefox":c.h(p,"MSIE")?"Internet Explorer":c.h(p,"Gecko")?"Mozilla":""},ka:function(){return/Windows/i.test(p)?/Phone/.test(p)?"Windows Mobile":"Windows":/(iPhone|iPad|iPod)/.test(p)?"iOS":/Android/.test(p)?"Android":/(BlackBerry|PlayBook|BB10)/i.test(p)?"BlackBerry":/Mac/i.test(p)?"Mac OS X":/Linux/.test(p)?"Linux":""},Da:function(){return/iPhone/.test(p)?
"iPhone":/iPad/.test(p)?"iPad":/iPod/.test(p)?"iPod Touch":/(BlackBerry|PlayBook|BB10)/i.test(p)?"BlackBerry":/Windows Phone/i.test(p)?"Windows Phone":/Android/.test(p)?"Android":""},ma:function(a){a=a.split("/");return 3<=a.length?a[2]:""},z:function(){return c.pa({$os:c.info.ka(),$browser:c.info.Z(),$referrer:q.referrer,$referring_domain:c.info.ma(q.referrer),$device:c.info.Da(),mp_lib:"web"})},Qa:function(a){return c.pa({mp_page:a,mp_referrer:q.referrer,mp_browser:c.info.Z(),mp_platform:c.info.ka()})}};
var s={log:function(){if(A&&!c.d(u)&&u)try{u.log.apply(u,arguments)}catch(a){c.a(arguments,function(a){u.log(a)})}},error:function(){if(A&&!c.d(u)&&u){var a=["Mixpanel error:"].concat(c.m(arguments));try{u.error.apply(u,a)}catch(b){c.a(a,function(a){u.error(a)})}}},aa:function(){if(!c.d(u)&&u){var a=["Mixpanel error:"].concat(c.m(arguments));try{u.error.apply(u,a)}catch(b){c.a(a,function(a){u.error(a)})}}}};w.prototype.w=C();w.prototype.N=C();w.prototype.L=C();w.prototype.R=function(a){this.ia=a;
return this};w.prototype.o=function(a,b,d,h){var e=this,i=c.Fa(a);if(0==i.length)s.error("The DOM query ("+a+") returned 0 elements");else return c.a(i,function(a){c.na(a,this.la,function(a){var c={},i=e.w(d,this),j=e.ia.e("track_links_timeout");e.N(a,this,c);window.setTimeout(e.qa(h,i,c,l),j);e.ia.o(b,i,e.qa(h,i,c))})},this),l};w.prototype.qa=function(a,b,c,h){var h=h||v,e=this;return function(){if(!c.Aa)c.Aa=l,a&&a(h,b)===v||e.L(b,c,h)}};w.prototype.w=function(a,b){return"function"===typeof a?a(b):
c.extend({},a)};c.ga(B,w);B.prototype.w=function(a,b){var c=B.Va.w.apply(this,arguments);if(b.href)c.url=b.href;return c};B.prototype.N=function(a,b,c){c.ja=2===a.which||a.metaKey||"_blank"===b.target;c.href=b.href;c.ja||a.preventDefault()};B.prototype.L=function(a,b){b.ja||setTimeout(function(){window.location=b.href},0)};c.ga(F,w);F.prototype.N=function(a,b,c){c.element=b;a.preventDefault()};F.prototype.L=function(a,b){setTimeout(function(){b.element.submit()},0)};k.prototype.z=function(){var a=
{};c.a(this.props,function(b,d){c.ea(O,d)||(a[d]=b)});return a};k.prototype.load=function(){if(!this.disabled){var a=c.cookie.parse(this.name);a&&(this.props=c.extend({},a))}};k.prototype.$a=function(a){var b=a.upgrade,d;if(b)d="mp_super_properties","string"===typeof b&&(d=b),b=c.cookie.parse(d),c.cookie.remove(d),c.cookie.remove(d,l),b&&(this.props=c.extend(this.props,b.all,b.events));if(!a.cookie_name&&"mixpanel"!==a.name&&(d="mp_"+a.token+"_"+a.name,b=c.cookie.parse(d)))c.cookie.remove(d),c.cookie.remove(d,
l),this.j(b)};k.prototype.save=function(){this.disabled||c.cookie.set(this.name,c.p(this.props),this.O,this.M)};k.prototype.remove=function(){c.cookie.remove(this.name,v);c.cookie.remove(this.name,l)};k.prototype.clear=function(){this.remove();this.props={}};k.prototype.j=function(a,b,d){return c.g(a)?("undefined"===typeof b&&(b="None"),this.O="undefined"===typeof d?this.ba:d,c.a(a,function(a,c){if(!this.props[c]||this.props[c]===b)this.props[c]=a},this),this.save(),l):v};k.prototype.l=function(a,
b){return c.g(a)?(this.O="undefined"===typeof b?this.ba:b,c.extend(this.props,a),this.save(),l):v};k.prototype.T=function(a){a in this.props&&(delete this.props[a],this.save())};k.prototype.Za=function(){if(!this.$)this.j(c.info.Ba()),this.$=l};k.prototype.ua=function(a){this.l(c.info.Sa(a))};k.prototype.ta=function(a){this.j({$initial_referrer:a||"$direct",$initial_referring_domain:c.info.ma(a)||"$direct"},"")};k.prototype.sa=function(a){this.ba=this.O=a.cookie_expiration;this.Ua(a.disable_cookie);
this.Ta(a.cross_subdomain_cookie)};k.prototype.Ua=function(a){(this.disabled=a)&&this.remove()};k.prototype.Ta=function(a){if(a!==this.M)this.M=a,this.remove(),this.save()};k.prototype.Ia=function(){return this.M};k.prototype.D=function(a,b){var d=this.u(a),h=b[a],e=this.G("$set"),i=this.G("$add"),j=this.G("$append",[]);"__mps"===d?(c.extend(e,h),this.J("$add",h)):"__mpa"===d?c.a(h,function(a,b){b in e?e[b]+=a:(b in i||(i[b]=0),i[b]+=a)},this):"__mpap"===d&&j.push(h);s.log("MIXPANEL PEOPLE REQUEST (QUEUED, PENDING IDENTIFY):");
s.log(b);this.save()};k.prototype.J=function(a,b){var d=this.s(a);c.d(d)||(c.a(b,function(a,b){delete d[b]},this),this.save())};k.prototype.u=function(a){if("$set"===a)return"__mps";if("$add"===a)return"__mpa";if("$append"===a)return"__mpap";s.error("Invalid queue:",a)};k.prototype.s=function(a){return this.props[this.u(a)]};k.prototype.G=function(a,b){var d=this.u(a),b=c.d(b)?{}:b;return this.props[d]||(this.props[d]=b)};g.prototype.R=function(a,b,c){if("undefined"===typeof c)s.error("You must name your new library: init(token, config, name)");
else if("mixpanel"===c)s.error("You must initialize the main mixpanel object right after you include the Mixpanel js snippet");else return a=E(a,b,c),t[c]=a,a.I(),a};g.prototype.H=function(a,b,d){this.__loaded=l;this.config={};this.oa(c.extend({},P,b,{name:d,token:a,callback_fn:("mixpanel"===d?d:"mixpanel."+d)+"._jsc"}));this._jsc=C();this.B=[];this.C=[];this.A=[];this.q={disable_all_events:v,identify_called:v};this.cookie=new k(this.config)};g.prototype.I=function(){this.e("loaded")(this);this.e("track_pageview")&&
this.ra()};g.prototype.xa=function(){c.a(this.B,function(a){this.K.apply(this,a)},this);c.a(this.C,function(a){this.i.apply(this,a)},this);delete this.B;delete this.C};g.prototype.K=function(a,b){if(this.e("img"))return s.error("You can't use DOM tracking functions with img = true."),v;if(!J)return this.B.push([a,b]),v;var c=(new a).R(this);return c.o.apply(c,b)};g.prototype.X=function(a,b){if(c.d(a))return o;if(H)return function(c){a(c,b)};var d=this._jsc,h=""+Math.floor(1E8*Math.random()),e=this.e("callback_fn")+
'["'+h+'"]';d[h]=function(c){delete d[h];a(c,b)};return e};g.prototype.i=function(a,b,d){if(K)this.C.push(arguments);else if(this.e("test")&&(b.test=1),this.e("img")&&(b.img=1),d&&!H&&(b.callback=d),b.ip=this.e("ip")?1:0,b._=(new Date).getTime().toString(),a+="?"+c.va(b),"img"in b){var h=q.createElement("img");h.src=a;q.body.appendChild(h)}else if(H){var e=new XMLHttpRequest;e.open("GET",a,l);e.onreadystatechange=function(){4===e.readyState&&(200===e.status?d&&d(Number(e.responseText)):(s.error("Bad HTTP status",
e.status+" "+e.statusText),d&&d(0)))};e.send(o)}else{h=q.createElement("script");h.type="text/javascript";h.async=l;h.defer=l;h.src=a;var i=q.getElementsByTagName("script")[0];i.parentNode.insertBefore(h,i)}};g.prototype.F=function(a){function b(a,b){c.a(a,function(a){this[a[0]].apply(this,a.slice(1))},b)}var d,h=[],e=[];c.a(a,function(a){a&&(d=a[0],"function"===typeof a?a.call(this):c.isArray(a)&&-1!=d.indexOf("track")&&"function"===typeof this[d]?e.push(a):h.push(a))},this);b(h,this);b(e,this)};
g.prototype.push=function(a){this.F([a])};g.prototype.disable=function(a){"undefined"===typeof a?this.q.Ea=l:this.A=this.A.concat(a)};g.prototype.o=function(a,b,d){if("undefined"===typeof a)s.error("No event name provided to mixpanel.track");else if(c.La()||this.q.Ea||c.ea(this.A,a))"undefined"!==typeof d&&d(0);else return b=b||{},b.token=b.fb||this.e("token"),this.j({distinct_id:c.wa()},""),this.cookie.ua(q.referrer),this.e("store_google")&&this.cookie.Za(),this.e("save_referrer")&&this.cookie.ta(q.referrer),
b=c.extend({},c.info.z(),this.cookie.z(),b),a=c.truncate({event:a,properties:b},255),b=c.p(a),b=c.Y(b),s.log("MIXPANEL REQUEST:"),s.log(a),this.i(this.e("api_host")+"/track/",{data:b},this.X(d,a)),a};g.prototype.ra=function(a){if("undefined"===typeof a)a=q.location.href;this.o("mp_page_view",c.info.Qa(a))};g.prototype.Ya=function(){return this.K.call(this,B,arguments)};g.prototype.Xa=function(){return this.K.call(this,F,arguments)};g.prototype.l=function(a,b){this.cookie.l(a,b)};g.prototype.j=function(a,
b,c){this.cookie.j(a,b,c)};g.prototype.T=function(a){this.cookie.T(a)};g.prototype.v=function(a,b){var c={};c[a]=b;this.l(c)};g.prototype.Q=function(a){this.v("distinct_id",a)};g.prototype.k=function(){return this.P("distinct_id")};g.prototype.Pa=function(a){this.v("mp_name_tag",a)};g.prototype.oa=function(a){c.g(a)&&(c.extend(this.config,a),this.cookie&&this.cookie.sa(this.config),A=A||this.e("debug"))};g.prototype.e=function(a){return this.config[a]};g.prototype.P=function(a){return this.cookie.props[a]};
g.prototype.toString=function(){var a=this.e("name");"mixpanel"!==a&&(a="mixpanel."+a);return a};m.prototype.H=function(a){this.c=a};m.prototype.Q=function(a,b,d,h){var e=this.c.k();!c.d(e)&&e!==o&&e!==a&&this.set({$events_distinct_id:e});this.c.q.Ja=l;this.c.v("$people_distinct_id",a);this.za(b,d,h)};m.prototype.set=function(a,b,d){var h={},e={};c.g(a)?(c.a(a,function(a,b){"$distinct_id"==b||"$token"==b||(e[b]=a)}),d=b):e[a]=b;h.$set=e;return this.i(h,d)};m.prototype.fa=function(a,b,d){var h={},
e={};c.g(a)?(c.a(a,function(a,b){"$distinct_id"==b||"$token"==b||(isNaN(parseFloat(a))?s.error("Invalid increment value passed to mixpanel.people.increment - must be a number"):e[b]=a)}),d=b):(c.d(b)&&(b=1),e[a]=b);h.$add=e;return this.i(h,d)};m.prototype.append=function(a,b,d){var h={},e={};c.g(a)?(c.a(a,function(a,b){"$distinct_id"==b||"$token"==b||(e[b]=a)}),d=b):e[a]=b;h.$append=e;return this.i(h,d)};m.prototype.Wa=function(a,b){if(!c.Oa(a)&&(a=parseFloat(a),isNaN(a))){s.error("Invalid value passed to mixpanel.people.track_charge - must be a number");
return}return this.append("$transactions",{amount:a,time:new Date},b)};m.prototype.Ca=function(){if(this.W())return this.i({$delete:this.k()});s.error("mixpanel.people.delete_user() requires you to call identify() first")};m.prototype.toString=function(){return this.c.toString()+".people"};m.prototype.i=function(a,b){a.$token=this.V("token");a.$distinct_id=this.k();var d=c.ca(a),h=c.truncate(d,255),d=c.p(d),d=c.Y(d);if(!this.W())return this.ya(a),c.d(b)||b(-1),h;s.log("MIXPANEL PEOPLE REQUEST:");
s.log(h);this.c.i(this.V("api_host")+"/engage/",{data:d},this.c.X(b,h));return h};m.prototype.V=function(a){return this.c.e(a)};m.prototype.W=function(){return this.c.q.Ja===l};m.prototype.k=function(){return this.c.P("$people_distinct_id")};m.prototype.ya=function(a){"$set"in a?this.c.cookie.D("$set",a):"$add"in a?this.c.cookie.D("$add",a):"$append"in a?this.c.cookie.D("$append",a):s.error("Invalid call to _enqueue():",a)};m.prototype.za=function(a,b,d){var h=this,e=this.c.cookie.s("$set"),i=this.c.cookie.s("$add");
$append_queue=this.c.cookie.s("$append");!c.d(e)&&!c.S(e)&&this.set(e,function(b,d){1==b&&h.c.cookie.J("$set",e);c.d(a)||a(b,d)});!c.d(i)&&!c.S(i)&&this.fa(i,function(a,d){1==a&&h.c.cookie.J("$add",i);c.d(b)||b(a,d)});if(!c.d($append_queue)&&$append_queue.length){var g=[],f=function(){if($append_queue.length){var a=$append_queue.shift();h.append(a,function(b,e){0==b&&g.push(a);c.d(d)||d(b,e);f()})}else{var b=h.c.cookie.u("$append");h.c.v(b,g)}};f()}};c.toArray=c.m;c.isObject=c.g;c.JSONEncode=c.p;
c.JSONDecode=c.U;c.isEmptyObject=c.S;g.prototype.init=g.prototype.R;g.prototype.disable=g.prototype.disable;g.prototype.track=g.prototype.o;g.prototype.track_links=g.prototype.Ya;g.prototype.track_forms=g.prototype.Xa;g.prototype.track_pageview=g.prototype.ra;g.prototype.register=g.prototype.l;g.prototype.register_once=g.prototype.j;g.prototype.unregister=g.prototype.T;g.prototype.identify=g.prototype.Q;g.prototype.name_tag=g.prototype.Pa;g.prototype.set_config=g.prototype.oa;g.prototype.get_config=
g.prototype.e;g.prototype.get_property=g.prototype.P;g.prototype.get_distinct_id=g.prototype.k;g.prototype.toString=g.prototype.toString;k.prototype.properties=k.prototype.z;k.prototype.update_search_keyword=k.prototype.ua;k.prototype.update_referrer_info=k.prototype.ta;k.prototype.get_cross_subdomain=k.prototype.Ia;k.prototype.clear=k.prototype.clear;m.prototype.set=m.prototype.set;m.prototype.increment=m.prototype.fa;m.prototype.append=m.prototype.append;m.prototype.track_charge=m.prototype.Wa;
m.prototype.delete_user=m.prototype.Ca;m.prototype.identify=m.prototype.Q;m.prototype.get_distinct_id=m.prototype.k;m.prototype.toString=m.prototype.toString;if(c.d(t))s.aa("'mixpanel' object not initialized. Ensure you are using the latest version of the Mixpanel JS Library along with the snippet we provide.");else if(t.__loaded||t.config&&t.cookie)s.error("Mixpanel library has already been downloaded at least once.");else if(1.1>z)s.aa("Version mismatch; please ensure you're using the latest version of the Mixpanel code snippet.");
else{var y={};c.a(t._i,function(a){var b;a&&c.isArray(a)&&(b=a[a.length-1],a=E.apply(this,a),y[b]=a)});var Q=function(){c.a(y,function(a,b){"mixpanel"!==b&&(t[b]=a)});t._=c};t.init=function(a,b,c){c?t[c]||(t[c]=y[c]=E(a,b,c),t[c].I()):(c=t,y.mixpanel?c=y.mixpanel:a&&(c=E(a,b,"mixpanel")),window.mixpanel=t=c,Q())};t.init();c.a(y,function(a){a.I()});if(q.addEventListener)"complete"==q.readyState?x():q.addEventListener("DOMContentLoaded",x,v);else if(q.attachEvent){q.attachEvent("onreadystatechange",
x);z=v;try{z=window.frameElement==o}catch(R){}if(q.documentElement.doScroll&&z){var N=function(){try{q.documentElement.doScroll("left")}catch(a){setTimeout(N,1);return}x()};N()}}c.na(window,"load",x,l)}})(window.mixpanel);
})();
